# This workflow builds the Linux self-hosted GitHub Runner disk image.
name: 'GitHub Runner: Build Linux Image'

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: registry.opensuse.org/opensuse/leap:15
      options: --privileged
    steps:
    - run: >-
        zypper --non-interactive install python3-kiwi kiwi-systemdeps-disk-images sudo tar
    - run: echo 'ALL ALL=(ALL:ALL) NOPASSWD:ALL' > /etc/sudoers.d/nopasswd
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        persist-credentials: false
        sparse-checkout: src/disk-images/github-runner-linux
    - run: ./build-image.sh
      working-directory: src/disk-images/github-runner-linux
    - uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
      with:
        name: github-runner-image.qcow2.zip
        path: src/disk-images/github-runner-linux/*.qcow2
        if-no-files-found: error
