# This workflow builds the GitHub runner
name: 'GitHub Runner: Build Monitor'

on:
  push:
    paths: [ src/go/github-runner-monitor/** ]
  pull_request:
    paths: [ src/go/github-runner-monitor/** ]
  workflow_dispatch:

permissions:
  # This uses external actions, lock things down to read-only.
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        persist-credentials: false
        sparse-checkout: |
          src/go/github-runner-monitor
          .github/workflows/config
    - uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
      with:
        go-version-file: go.work
        cache-dependency-path: src/go/github-runner-monitor/go.sum
    - run: go build .
      working-directory: src/go/github-runner-monitor
      env:
        CGO_ENABLED: '0'
        GOWORK: off
    - uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b # v4.5.0
      with:
        name: github-runner-linux
        path: src/go/github-runner-monitor/github-runner-monitor
        if-no-files-found: error
    - uses: golangci/golangci-lint-action@971e284b6050e8a5849b72094c50ab08da042db8 # v6.1.1
      # This is only safe because this workflow does not allow writing
      with:
        args: --config=${{ github.workspace }}/.github/workflows/config/.golangci.yaml  --verbose --timeout 3m
        working-directory: src/go/github-runner-monitor
        only-new-issues: true
      env:
        GOWORK: off
