# This workflow builds the GitHub runner
name: 'GitHub Runner: Build Monitor'

on:
  push:
    paths: [ src/go/github-runner-monitor/** ]
  pull_request:
    paths: [ src/go/github-runner-monitor/** ]
  workflow_dispatch:

permissions:
  # This uses external actions, lock things down to read-only.
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
        sparse-checkout: |
          src/go/github-runner-monitor
          .github/workflows/config
    - uses: actions/setup-go@v5
      with:
        go-version-file: go.work
        cache-dependency-path: src/go/github-runner-monitor/go.sum
    - run: go build .
      working-directory: src/go/github-runner-monitor
      env:
        CGO_ENABLED: '0'
        GOWORK: off
    - uses: actions/upload-artifact@v4
      with:
        name: github-runner-linux
        path: src/go/github-runner-monitor/github-runner-monitor
        if-no-files-found: error
    - uses: golangci/golangci-lint-action@v6.1.1
      # This is only safe because this workflow does not allow writing
      with:
        args: --config=${{ github.workspace }}/.github/workflows/config/.golangci.yaml  --verbose --timeout 3m
        working-directory: src/go/github-runner-monitor
        only-new-issues: true
      env:
        GOWORK: off
